// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Budget.Api.Data.Entities;

public partial class Account
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Type { get; set; }

    public decimal StartingBalance { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();
}