// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BudgetApp.Data.Entities;

public partial class Budget
{
    public int Id { get; set; }

    public int CategoryId { get; set; }

    public decimal Amount { get; set; }

    public int Month { get; set; }

    public int Year { get; set; }

    public virtual Category Category { get; set; }
}