// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BudgetApp.Data.Entities;

public partial class Category
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Type { get; set; }

    public int? ParentCategoryId { get; set; }

    public virtual ICollection<Budget> Budgets { get; set; } = new List<Budget>();

    public virtual ICollection<Category> InverseParentCategory { get; set; } = new List<Category>();

    public virtual Category ParentCategory { get; set; }

    public virtual ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();
}