// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BudgetApp.Data.Entities;

public partial class Transaction
{
    public int Id { get; set; }

    public int AccountId { get; set; }

    public int CategoryId { get; set; }

    public decimal Amount { get; set; }

    public DateOnly Date { get; set; }

    public string Description { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Account Account { get; set; }

    public virtual Category Category { get; set; }
}